## Creating Dataframe

In [2]:
import pandas as pd

In [4]:
oil = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\oil.csv")

In [6]:
oil

            date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1218 rows x 2 columns]

In [8]:
oil.shape

(1218, 2)

In [10]:
oil.index

RangeIndex(start=0, stop=1218, step=1)

In [12]:
oil.columns

Index(['date', 'dcoilwtico'], dtype='object')

In [14]:
oil.columns = ['price_date', 'oil_price']

In [16]:
oil.columns

Index(['price_date', 'oil_price'], dtype='object')

In [18]:
oil

      price_date  oil_price
0     2013-01-01        NaN
1     2013-01-02      93.14
2     2013-01-03      92.97
3     2013-01-04      93.12
4     2013-01-07      93.20
...          ...        ...
1213  2017-08-25      47.65
1214  2017-08-28      46.40
1215  2017-08-29      46.46
1216  2017-08-30      45.96
1217  2017-08-31      47.26

[1218 rows x 2 columns]

In [20]:
oil.axes

[RangeIndex(start=0, stop=1218, step=1),
 Index(['price_date', 'oil_price'], dtype='object')]

In [22]:
oil.dtypes

price_date     object
oil_price     float64
dtype: object

## Dataframe: Heads, Tails & Sample

In [35]:
oil.sample(10)

      price_date  oil_price
496   2014-11-26      73.70
867   2016-04-28      46.03
1076  2017-02-15      53.11
443   2014-09-12      92.18
949   2016-08-22      46.80
266   2014-01-08      91.90
323   2014-03-28     101.73
909   2016-06-27      45.80
726   2015-10-14      46.63
756   2015-11-25      41.22

In [46]:
oil.sample(10, random_state=12345) #state to save the random sample as generated

      price_date  oil_price
656   2015-07-08      51.61
502   2014-12-04      66.73
111   2013-06-05      93.66
1134  2017-05-08      46.46
931   2016-07-27      41.90
65    2013-04-02      97.23
925   2016-07-19      44.64
837   2016-03-17      40.17
981   2016-10-05      49.75
984   2016-10-10      49.76

## Assignment 1

In [1]:
import pandas as pd
transactions = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\transactions.csv")

In [3]:
transactions

             date  store_nbr  transactions
0      2013-01-01         25           770
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83488 rows x 3 columns]

In [5]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [7]:
transactions.shape

(83488, 3)

In [9]:
transactions.dtypes

date            object
store_nbr        int64
transactions     int64
dtype: object

## Dataframe: Info & Describe

In [17]:
oil = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\oil.csv")

In [19]:
oil

            date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1218 rows x 2 columns]

In [21]:
oil.head()

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20

In [25]:
oil.tail(7)

            date  dcoilwtico
1211  2017-08-23       48.45
1212  2017-08-24       47.24
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

In [27]:
oil.sample(5)

           date  dcoilwtico
748  2015-11-13       40.69
854  2016-04-11       40.46
514  2014-12-22       55.25
97   2013-05-16       94.85
299  2014-02-24      103.17

In [29]:
oil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   object
 1   dcoilwtico  1175 non-null   float64
dtypes: float64(1), object(1)
memory usage: 19.2+ KB

In [39]:
oil.describe()

        dcoilwtico
count  1175.000000
mean     67.714366
std      25.630476
min      26.190000
25%      46.405000
50%      53.190000
75%      95.660000
max     110.620000

In [41]:
oil.describe(include='all')

              date   dcoilwtico
count         1218  1175.000000
unique        1218          NaN
top     2013-01-01          NaN
freq             1          NaN
mean           NaN    67.714366
std            NaN    25.630476
min            NaN    26.190000
25%            NaN    46.405000
50%            NaN    53.190000
75%            NaN    95.660000
max            NaN   110.620000

### Assignment 2

In [50]:
import pandas as pd
transactions = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\transactions.csv")
transactions

             date  store_nbr  transactions
0      2013-01-01         25           770
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83488 rows x 3 columns]

In [54]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [62]:
transactions.isna().sum()

date            0
store_nbr       0
transactions    0
dtype: int64

In [52]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  object
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.9+ MB

In [58]:
transactions.describe(include='all')

              date     store_nbr  transactions
count        83488  83488.000000  83488.000000
unique        1682           NaN           NaN
top     2017-08-15           NaN           NaN
freq            54           NaN           NaN
mean           NaN     26.939237   1694.602158
std            NaN     15.608204    963.286644
min            NaN      1.000000      5.000000
25%            NaN     13.000000   1046.000000
50%            NaN     27.000000   1393.000000
75%            NaN     40.000000   2079.000000
max            NaN     54.000000   8359.000000

## Accessing Dataframe Columns

In [66]:
oil = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\oil.csv")

In [70]:
oil.columns = ['date', 'oil price']

oil.head()

         date  oil price
0  2013-01-01        NaN
1  2013-01-02      93.14
2  2013-01-03      92.97
3  2013-01-04      93.12
4  2013-01-07      93.20

In [72]:
oil.date

0       2013-01-01
1       2013-01-02
2       2013-01-03
3       2013-01-04
4       2013-01-07
           ...
1213    2017-08-25
1214    2017-08-28
1215    2017-08-29
1216    2017-08-30
1217    2017-08-31
Name: date, Length: 1218, dtype: object

In [76]:
oil['oil price']

0         NaN
1       93.14
2       92.97
3       93.12
4       93.20
        ...
1213    47.65
1214    46.40
1215    46.46
1216    45.96
1217    47.26
Name: oil price, Length: 1218, dtype: float64

In [78]:
oil.columns = ['date', 'price']

oil.head()

         date  price
0  2013-01-01    NaN
1  2013-01-02  93.14
2  2013-01-03  92.97
3  2013-01-04  93.12
4  2013-01-07  93.20

In [80]:
oil.price

0         NaN
1       93.14
2       92.97
3       93.12
4       93.20
        ...
1213    47.65
1214    46.40
1215    46.46
1216    45.96
1217    47.26
Name: price, Length: 1218, dtype: float64

In [90]:
oil[['price', 'date']]

      price        date
0       NaN  2013-01-01
1     93.14  2013-01-02
2     92.97  2013-01-03
3     93.12  2013-01-04
4     93.20  2013-01-07
...     ...         ...
1213  47.65  2017-08-25
1214  46.40  2017-08-28
1215  46.46  2017-08-29
1216  45.96  2017-08-30
1217  47.26  2017-08-31

[1218 rows x 2 columns]

## Dataframe data with ILOC & LOC

In [94]:
# Preferably use LOC with dataframes

In [96]:
oil = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\oil.csv")
oil.columns = ['date', 'price']

oil

            date  price
0     2013-01-01    NaN
1     2013-01-02  93.14
2     2013-01-03  92.97
3     2013-01-04  93.12
4     2013-01-07  93.20
...          ...    ...
1213  2017-08-25  47.65
1214  2017-08-28  46.40
1215  2017-08-29  46.46
1216  2017-08-30  45.96
1217  2017-08-31  47.26

[1218 rows x 2 columns]

In [100]:
oil['euro_price'] = oil['price'] * 1.1
oil.head()

         date  price  euro_price
0  2013-01-01    NaN         NaN
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520

In [102]:
oil.iloc[:10]

         date  price  euro_price
0  2013-01-01    NaN         NaN
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520
5  2013-01-08  93.21     102.531
6  2013-01-09  93.08     102.388
7  2013-01-10  93.81     103.191
8  2013-01-11  93.60     102.960
9  2013-01-14  94.27     103.697

In [104]:
oil.iloc[:10, :]

         date  price  euro_price
0  2013-01-01    NaN         NaN
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520
5  2013-01-08  93.21     102.531
6  2013-01-09  93.08     102.388
7  2013-01-10  93.81     103.191
8  2013-01-11  93.60     102.960
9  2013-01-14  94.27     103.697

In [112]:
oil.iloc[:10, -2:]

   price  euro_price
0    NaN         NaN
1  93.14     102.454
2  92.97     102.267
3  93.12     102.432
4  93.20     102.520
5  93.21     102.531
6  93.08     102.388
7  93.81     103.191
8  93.60     102.960
9  94.27     103.697

In [114]:
oil.loc[:5]

         date  price  euro_price
0  2013-01-01    NaN         NaN
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520
5  2013-01-08  93.21     102.531

In [116]:
oil.loc[:5, 'date']

0    2013-01-01
1    2013-01-02
2    2013-01-03
3    2013-01-04
4    2013-01-07
5    2013-01-08
Name: date, dtype: object

In [118]:
oil.loc[:5, ['date', 'euro_price']]

         date  euro_price
0  2013-01-01         NaN
1  2013-01-02     102.454
2  2013-01-03     102.267
3  2013-01-04     102.432
4  2013-01-07     102.520
5  2013-01-08     102.531

In [120]:
oil.loc[:5, ['euro_price','date']]

   euro_price        date
0         NaN  2013-01-01
1     102.454  2013-01-02
2     102.267  2013-01-03
3     102.432  2013-01-04
4     102.520  2013-01-07
5     102.531  2013-01-08

In [126]:
oil.loc[:5, ['date':'euro_price']]

SyntaxError: invalid syntax (4107364656.py, line 1)

In [128]:
oil.loc[:5, 'date':'euro_price']

         date  price  euro_price
0  2013-01-01    NaN         NaN
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520
5  2013-01-08  93.21     102.531

### Demo

In [ ]:
import pandas as pd


# Read the dataset into a DataFrame`
df = pd.read_csv(r'insurance_data.csv')

# Use .iloc to select the first three rows
first_three_rows = df.iloc[:3]

# Use .loc to select rows from index 3 to index 7
rows_from_3_to_7 = df.loc[3:7]

print(first_three_rows)
print(rows_from_3_to_7)

### Assignment 3

In [133]:
import pandas as pd
transactions = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\transactions.csv")
transactions

             date  store_nbr  transactions
0      2013-01-01         25           770
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83488 rows x 3 columns]

In [137]:
new_df = transactions[1:]
new_df

             date  store_nbr  transactions
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
5      2013-01-02          5          1903
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83487 rows x 3 columns]

In [143]:
new_df.store_nbr.nunique()

54

In [149]:
new_df.transactions.sum() / 1000000

141.478175

## Dropping Columns & Rows

In [200]:
oil = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\oil.csv")
oil.columns = ['date', 'price']
oil['euro_price'] = oil['price'] * 1.1
oil.head()

         date  price  euro_price
0  2013-01-01    NaN         NaN
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520

In [186]:
oil.drop('price', axis=1)

            date  euro_price
0     2013-01-01         NaN
1     2013-01-02     102.454
2     2013-01-03     102.267
3     2013-01-04     102.432
4     2013-01-07     102.520
...          ...         ...
1213  2017-08-25      52.415
1214  2017-08-28      51.040
1215  2017-08-29      51.106
1216  2017-08-30      50.556
1217  2017-08-31      51.986

[1218 rows x 2 columns]

In [188]:
oil.drop('price', axis=1, inplace=True)

In [190]:
oil

            date  euro_price
0     2013-01-01         NaN
1     2013-01-02     102.454
2     2013-01-03     102.267
3     2013-01-04     102.432
4     2013-01-07     102.520
...          ...         ...
1213  2017-08-25      52.415
1214  2017-08-28      51.040
1215  2017-08-29      51.106
1216  2017-08-30      50.556
1217  2017-08-31      51.986

[1218 rows x 2 columns]

In [194]:
oil_euro = oil.drop('price', axis=1)

In [196]:
oil_euro

            date  euro_price
0     2013-01-01         NaN
1     2013-01-02     102.454
2     2013-01-03     102.267
3     2013-01-04     102.432
4     2013-01-07     102.520
...          ...         ...
1213  2017-08-25      52.415
1214  2017-08-28      51.040
1215  2017-08-29      51.106
1216  2017-08-30      50.556
1217  2017-08-31      51.986

[1218 rows x 2 columns]

In [204]:
oil_euro = oil.drop(1, axis=0)

In [206]:
oil_euro

            date  price  euro_price
0     2013-01-01    NaN         NaN
2     2013-01-03  92.97     102.267
3     2013-01-04  93.12     102.432
4     2013-01-07  93.20     102.520
5     2013-01-08  93.21     102.531
...          ...    ...         ...
1213  2017-08-25  47.65      52.415
1214  2017-08-28  46.40      51.040
1215  2017-08-29  46.46      51.106
1216  2017-08-30  45.96      50.556
1217  2017-08-31  47.26      51.986

[1217 rows x 3 columns]

In [211]:
oil_euro.reset_index() #reseting index after removing row index number 1

      index        date  price  euro_price
0         0  2013-01-01    NaN         NaN
1         2  2013-01-03  92.97     102.267
2         3  2013-01-04  93.12     102.432
3         4  2013-01-07  93.20     102.520
4         5  2013-01-08  93.21     102.531
...     ...         ...    ...         ...
1212   1213  2017-08-25  47.65      52.415
1213   1214  2017-08-28  46.40      51.040
1214   1215  2017-08-29  46.46      51.106
1215   1216  2017-08-30  45.96      50.556
1216   1217  2017-08-31  47.26      51.986

[1217 rows x 4 columns]

## Identifying & Dropping Duplicates

In [218]:
oil = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\oil.csv")
oil.columns = ['date', 'price']
oil['euro_price'] = oil['price'] * 1.1
oil.head()

         date  price  euro_price
0  2013-01-01    NaN         NaN
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520

In [222]:
oil = pd.concat([oil, oil.iloc[[-1]]]).reset_index(drop=True)

oil.tail()

            date  price  euro_price
1214  2017-08-28  46.40      51.040
1215  2017-08-29  46.46      51.106
1216  2017-08-30  45.96      50.556
1217  2017-08-31  47.26      51.986
1218  2017-08-31  47.26      51.986

In [230]:
oil.shape

(1219, 3)

In [232]:
oil.nunique(dropna=False)

date          1218
price          999
euro_price     999
dtype: int64

In [236]:
oil.duplicated(subset='price')

0       False
1       False
2       False
3       False
4       False
        ...
1214     True
1215     True
1216    False
1217    False
1218     True
Length: 1219, dtype: bool

In [238]:
oil.duplicated(subset='price').sum()

220

In [242]:
oil.drop_duplicates()

            date  price  euro_price
0     2013-01-01    NaN         NaN
1     2013-01-02  93.14     102.454
2     2013-01-03  92.97     102.267
3     2013-01-04  93.12     102.432
4     2013-01-07  93.20     102.520
...          ...    ...         ...
1213  2017-08-25  47.65      52.415
1214  2017-08-28  46.40      51.040
1215  2017-08-29  46.46      51.106
1216  2017-08-30  45.96      50.556
1217  2017-08-31  47.26      51.986

[1218 rows x 3 columns]

In [244]:
oil.drop_duplicates(keep='last')

            date  price  euro_price
0     2013-01-01    NaN         NaN
1     2013-01-02  93.14     102.454
2     2013-01-03  92.97     102.267
3     2013-01-04  93.12     102.432
4     2013-01-07  93.20     102.520
...          ...    ...         ...
1213  2017-08-25  47.65      52.415
1214  2017-08-28  46.40      51.040
1215  2017-08-29  46.46      51.106
1216  2017-08-30  45.96      50.556
1218  2017-08-31  47.26      51.986

[1218 rows x 3 columns]

In [246]:
oil.drop_duplicates(keep='last', ignore_index=True)

            date  price  euro_price
0     2013-01-01    NaN         NaN
1     2013-01-02  93.14     102.454
2     2013-01-03  92.97     102.267
3     2013-01-04  93.12     102.432
4     2013-01-07  93.20     102.520
...          ...    ...         ...
1213  2017-08-25  47.65      52.415
1214  2017-08-28  46.40      51.040
1215  2017-08-29  46.46      51.106
1216  2017-08-30  45.96      50.556
1217  2017-08-31  47.26      51.986

[1218 rows x 3 columns]

In [250]:
oil.drop_duplicates(subset=['price'], ignore_index=True)

           date  price  euro_price
0    2013-01-01    NaN         NaN
1    2013-01-02  93.14     102.454
2    2013-01-03  92.97     102.267
3    2013-01-04  93.12     102.432
4    2013-01-07  93.20     102.520
..          ...    ...         ...
994  2017-08-15  47.57      52.327
995  2017-08-18  48.59      53.449
996  2017-08-21  47.39      52.129
997  2017-08-30  45.96      50.556
998  2017-08-31  47.26      51.986

[999 rows x 3 columns]

### Demo

In [ ]:
import pandas as pd

# Load the dataset which may contain duplicates
df = pd.read_csv('insurance_data_dup.csv')


# Drop duplicate rows, keep the last occurrence, and reset the index
df_no_duplicates = df.drop_duplicates(keep='last', ignore_index=True)


# Display the DataFrame after removing duplicates
df_no_duplicates

### Assignment 4

In [273]:
import pandas as pd
transactions = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\transactions.csv")
transactions

             date  store_nbr  transactions
0      2013-01-01         25           770
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83488 rows x 3 columns]

In [275]:
transactions.drop(0, axis=0, inplace=True)

In [277]:
transactions

             date  store_nbr  transactions
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
5      2013-01-02          5          1903
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83487 rows x 3 columns]

In [295]:
transactions.drop('date', axis=1, inplace=False).head()

   store_nbr  transactions
1          1          2111
2          2          2358
3          3          3487
4          4          1922
5          5          1903

In [293]:
transactions.drop_duplicates(subset=['store_nbr'], keep='last').head()

             date  store_nbr  transactions
83434  2017-08-15          1          1693
83435  2017-08-15          2          1737
83436  2017-08-15          3          2956
83437  2017-08-15          4          1283
83438  2017-08-15          5          1310

## Missing Data

In [ ]:
transactions.isna().sum()

In [ ]:
transactions.info()

In [ ]:
transactions.fillna()

In [ ]:
transactions.fillna({'price': 0})

In [ ]:
transactions.dropna()

In [ ]:
transactions.dropna(subset=['price'])

### Demo

In [ ]:
import pandas as pd

# Load the dataset which may have missing values in the 'age' column
df = pd.read_csv('insurance_data_missing.csv')

# Fill missing 'age' values with the string 'missing'
df.fillna({'age', 'missing'}, inplace=True)

# Display the DataFrame after filling missing values
df

### Assignment 5

In [301]:
oil = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\oil.csv")
oil

            date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1218 rows x 2 columns]

In [305]:
oil.isna().sum()

date           0
dcoilwtico    43
dtype: int64

In [319]:
oil['dcoilwtico'].fillna(0).mean()

65.32379310344828

In [323]:
oil['dcoilwtico'].fillna(oil['dcoilwtico'].mean()).mean()

67.71436595744682

## Filtering Dataframe

In [327]:
oil = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\oil.csv")
oil

            date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1218 rows x 2 columns]

In [329]:
oil['benchmark'] = 100

oil.head()

         date  dcoilwtico  benchmark
0  2013-01-01         NaN        100
1  2013-01-02       93.14        100
2  2013-01-03       92.97        100
3  2013-01-04       93.12        100
4  2013-01-07       93.20        100

In [331]:
oil.describe()

        dcoilwtico  benchmark
count  1175.000000     1218.0
mean     67.714366      100.0
std      25.630476        0.0
min      26.190000      100.0
25%      46.405000      100.0
50%      53.190000      100.0
75%      95.660000      100.0
max     110.620000      100.0

In [333]:
oil.loc[oil['dcoilwtico'] > 100]

           date  dcoilwtico  benchmark
131  2013-07-03      101.92        100
133  2013-07-05      103.09        100
134  2013-07-08      103.03        100
135  2013-07-09      103.46        100
136  2013-07-10      106.41        100
..          ...         ...        ...
407  2014-07-24      102.76        100
408  2014-07-25      105.23        100
409  2014-07-28      105.68        100
410  2014-07-29      104.91        100
411  2014-07-30      104.29        100

[182 rows x 3 columns]

In [335]:
oil.loc[oil['dcoilwtico'] > oil['benchmark']]

           date  dcoilwtico  benchmark
131  2013-07-03      101.92        100
133  2013-07-05      103.09        100
134  2013-07-08      103.03        100
135  2013-07-09      103.46        100
136  2013-07-10      106.41        100
..          ...         ...        ...
407  2014-07-24      102.76        100
408  2014-07-25      105.23        100
409  2014-07-28      105.68        100
410  2014-07-29      104.91        100
411  2014-07-30      104.29        100

[182 rows x 3 columns]

In [339]:
oil.loc[oil['date'].str[:4] == '2013']

           date  dcoilwtico  benchmark
0    2013-01-01         NaN        100
1    2013-01-02       93.14        100
2    2013-01-03       92.97        100
3    2013-01-04       93.12        100
4    2013-01-07       93.20        100
..          ...         ...        ...
256  2013-12-25         NaN        100
257  2013-12-26       99.18        100
258  2013-12-27       99.94        100
259  2013-12-30       98.90        100
260  2013-12-31       98.17        100

[261 rows x 3 columns]

In [353]:
mask = (oil['dcoilwtico'] > oil['benchmark']) & (oil['date'].str[:4] == '2013')

In [355]:
oil.loc[mask]

           date  dcoilwtico  benchmark
131  2013-07-03      101.92        100
133  2013-07-05      103.09        100
134  2013-07-08      103.03        100
135  2013-07-09      103.46        100
136  2013-07-10      106.41        100
..          ...         ...        ...
204  2013-10-14      102.46        100
205  2013-10-15      101.15        100
206  2013-10-16      102.34        100
207  2013-10-17      100.72        100
208  2013-10-18      100.87        100

[76 rows x 3 columns]

## Filtering Dataframe: QUERY Method

In [368]:
oil = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\oil.csv",
                 parse_dates=['date'])
oil

           date  dcoilwtico
0    2013-01-01         NaN
1    2013-01-02       93.14
2    2013-01-03       92.97
3    2013-01-04       93.12
4    2013-01-07       93.20
...         ...         ...
1213 2017-08-25       47.65
1214 2017-08-28       46.40
1215 2017-08-29       46.46
1216 2017-08-30       45.96
1217 2017-08-31       47.26

[1218 rows x 2 columns]

In [379]:
oil['benchmark'] = 100

oil.head()

        date  dcoilwtico  benchmark
0 2013-01-01         NaN        100
1 2013-01-02       93.14        100
2 2013-01-03       92.97        100
3 2013-01-04       93.12        100
4 2013-01-07       93.20        100

In [383]:
oil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   datetime64[ns]
 1   dcoilwtico  1175 non-null   float64
 2   benchmark   1218 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 28.7 KB

In [385]:
oil.dtypes

date          datetime64[ns]
dcoilwtico           float64
benchmark              int64
dtype: object

In [387]:
oil.query(
    "dcoilwtico > benchmark or date.dt.year == 2013"
)

          date  dcoilwtico  benchmark
0   2013-01-01         NaN        100
1   2013-01-02       93.14        100
2   2013-01-03       92.97        100
3   2013-01-04       93.12        100
4   2013-01-07       93.20        100
..         ...         ...        ...
407 2014-07-24      102.76        100
408 2014-07-25      105.23        100
409 2014-07-28      105.68        100
410 2014-07-29      104.91        100
411 2014-07-30      104.29        100

[367 rows x 3 columns]

### Demo

In [ ]:
import pandas as pd

# Load the dataset
df = pd.read_csv('insurance_data.csv')

# Use the query method to find all smokers in the 'southeast' region
smokers_southeast = df.query(
    "smoker == 'yes' and region =='southeast'"
)

# Display the result
smokers_southeast

### Assignment 6

In [510]:
import pandas as pd
transactions = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\transactions.csv")
transactions

             date  store_nbr  transactions
0      2013-01-01         25           770
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83488 rows x 3 columns]

In [512]:
#
(transactions['transactions'] > 2000).mean()

0.26680481027213493

In [514]:
#Task2
mask = (transactions['transactions'] > 2000) & (transactions['store_nbr'] == 25)

In [516]:
transactions.loc[mask, 'transactions'].count() / transactions.loc[(transactions['store_nbr'] == 25), 'transactions'].count()

0.0346749226006192

In [518]:
#Task 3

In [532]:
transactions.query(
    "store_nbr in (25, 31) and date.str[6] in ['5', '6'] and transactions < 2000"
).sum().iloc[2]

644910

## Sorting Dataframes

In [536]:
oil.sort_index(ascending=False)

           date  dcoilwtico  benchmark
1217 2017-08-31       47.26        100
1216 2017-08-30       45.96        100
1215 2017-08-29       46.46        100
1214 2017-08-28       46.40        100
1213 2017-08-25       47.65        100
...         ...         ...        ...
4    2013-01-07       93.20        100
3    2013-01-04       93.12        100
2    2013-01-03       92.97        100
1    2013-01-02       93.14        100
0    2013-01-01         NaN        100

[1218 rows x 3 columns]

In [550]:
oil.sort_index(ascending=True, axis = 1)

      benchmark       date  dcoilwtico
0           100 2013-01-01         NaN
1           100 2013-01-02       93.14
2           100 2013-01-03       92.97
3           100 2013-01-04       93.12
4           100 2013-01-07       93.20
...         ...        ...         ...
1213        100 2017-08-25       47.65
1214        100 2017-08-28       46.40
1215        100 2017-08-29       46.46
1216        100 2017-08-30       45.96
1217        100 2017-08-31       47.26

[1218 rows x 3 columns]

In [556]:
oil['month'] = oil['date'].astype('datetime64[ns]').dt.month

oil

           date  dcoilwtico  benchmark  month
0    2013-01-01         NaN        100      1
1    2013-01-02       93.14        100      1
2    2013-01-03       92.97        100      1
3    2013-01-04       93.12        100      1
4    2013-01-07       93.20        100      1
...         ...         ...        ...    ...
1213 2017-08-25       47.65        100      8
1214 2017-08-28       46.40        100      8
1215 2017-08-29       46.46        100      8
1216 2017-08-30       45.96        100      8
1217 2017-08-31       47.26        100      8

[1218 rows x 4 columns]

In [558]:
oil.sort_values('dcoilwtico')

           date  dcoilwtico  benchmark  month
812  2016-02-11       26.19        100      2
796  2016-01-20       26.68        100      1
811  2016-02-10       27.54        100      2
810  2016-02-09       27.96        100      2
795  2016-01-19       28.47        100      1
...         ...         ...        ...    ...
1079 2017-02-20         NaN        100      2
1118 2017-04-14         NaN        100      4
1149 2017-05-29         NaN        100      5
1174 2017-07-03         NaN        100      7
1175 2017-07-04         NaN        100      7

[1218 rows x 4 columns]

In [560]:
oil.sort_values('dcoilwtico', ascending=False)

           date  dcoilwtico  benchmark  month
178  2013-09-06      110.62        100      9
171  2013-08-28      110.17        100      8
179  2013-09-09      109.62        100      9
170  2013-08-27      109.11        100      8
182  2013-09-12      108.72        100      9
...         ...         ...        ...    ...
1079 2017-02-20         NaN        100      2
1118 2017-04-14         NaN        100      4
1149 2017-05-29         NaN        100      5
1174 2017-07-03         NaN        100      7
1175 2017-07-04         NaN        100      7

[1218 rows x 4 columns]

In [562]:
oil.sort_values(['month', 'dcoilwtico'], ascending=[True, False])

           date  dcoilwtico  benchmark  month
282  2014-01-30       98.25        100      1
21   2013-01-30       97.98        100      1
22   2013-01-31       97.65        100      1
20   2013-01-29       97.62        100      1
283  2014-01-31       97.55        100      1
...         ...         ...        ...    ...
774  2015-12-21       34.55        100     12
256  2013-12-25         NaN        100     12
517  2014-12-25         NaN        100     12
778  2015-12-25         NaN        100     12
1039 2016-12-26         NaN        100     12

[1218 rows x 4 columns]

### Demo

In [ ]:
import pandas as pd

# Load the dataset
df = pd.read_csv("insurance_data.csv")

# Sort the DataFrame by 'smoker' status and 'age', with smokers first and youngest ages first
sorted_df = df.sort_values(['smoker', 'age'], ascending=[False, True])

# Display the sorted DataFrame
sorted_df

### Assignment 7

In [591]:
import pandas as pd
transactions = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\transactions.csv")
transactions = transactions.drop(index=transactions.index[0])
transactions

             date  store_nbr  transactions
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
5      2013-01-02          5          1903
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83487 rows x 3 columns]

In [593]:
transactions.sort_values('transactions', ascending=False).head()

             date  store_nbr  transactions
52011  2015-12-23         44          8359
71010  2016-12-23         44          8307
16570  2013-12-23         44          8256
33700  2014-12-23         44          8120
16572  2013-12-23         46          8001

In [595]:
transactions.sort_values(['date', 'transactions'], ascending=[True, False])

             date  store_nbr  transactions
40     2013-01-02         46          4886
38     2013-01-02         44          4821
39     2013-01-02         45          4208
41     2013-01-02         47          4161
11     2013-01-02         11          3547
...           ...        ...           ...
83455  2017-08-15         22           766
83449  2017-08-15         16           742
83465  2017-08-15         32           615
83468  2017-08-15         35           612
83459  2017-08-15         26           534

[83487 rows x 3 columns]

In [597]:
transactions.sort_index(axis=1, ascending=False)

       transactions  store_nbr        date
1              2111          1  2013-01-02
2              2358          2  2013-01-02
3              3487          3  2013-01-02
4              1922          4  2013-01-02
5              1903          5  2013-01-02
...             ...        ...         ...
83483          2804         50  2017-08-15
83484          1573         51  2017-08-15
83485          2255         52  2017-08-15
83486           932         53  2017-08-15
83487           802         54  2017-08-15

[83487 rows x 3 columns]

## Renaming & Reordering Columns

### Demo

In [ ]:
import pandas as pd

# Load the dataset
df = pd.read_csv("insurance_data.csv")

# Reorder the DataFrame columns using the 'labels' parameter
reordered_df = df.reindex(
    labels=["charges", "smoker", "age", "sex", "bmi", "children", "region"],
    axis=1
)

# Display the reordered DataFrame
reordered_df

### Assignment 8

In [607]:
transactions = transactions.rename(columns={'date': 'date', 'store_nbr': 'store_number', 'transactions': 'transaction_count'} )

transactions

             date  store_number  transaction_count
1      2013-01-02             1               2111
2      2013-01-02             2               2358
3      2013-01-02             3               3487
4      2013-01-02             4               1922
5      2013-01-02             5               1903
...           ...           ...                ...
83483  2017-08-15            50               2804
83484  2017-08-15            51               1573
83485  2017-08-15            52               2255
83486  2017-08-15            53                932
83487  2017-08-15            54                802

[83487 rows x 3 columns]

In [613]:
transactions.reindex(labels = ['date', 'transaction_count', 'store_number'], axis = 1).head()

         date  transaction_count  store_number
1  2013-01-02               2111             1
2  2013-01-02               2358             2
3  2013-01-02               3487             3
4  2013-01-02               1922             4
5  2013-01-02               1903             5

## Arithmetic & Boolean Column Creation

In [619]:
oil

           date  dcoilwtico  benchmark  month
0    2013-01-01         NaN        100      1
1    2013-01-02       93.14        100      1
2    2013-01-03       92.97        100      1
3    2013-01-04       93.12        100      1
4    2013-01-07       93.20        100      1
...         ...         ...        ...    ...
1213 2017-08-25       47.65        100      8
1214 2017-08-28       46.40        100      8
1215 2017-08-29       46.46        100      8
1216 2017-08-30       45.96        100      8
1217 2017-08-31       47.26        100      8

[1218 rows x 4 columns]

In [625]:
oil = oil.drop('month', axis = 1)
oil

           date  dcoilwtico  benchmark
0    2013-01-01         NaN        100
1    2013-01-02       93.14        100
2    2013-01-03       92.97        100
3    2013-01-04       93.12        100
4    2013-01-07       93.20        100
...         ...         ...        ...
1213 2017-08-25       47.65        100
1214 2017-08-28       46.40        100
1215 2017-08-29       46.46        100
1216 2017-08-30       45.96        100
1217 2017-08-31       47.26        100

[1218 rows x 3 columns]

In [627]:
oil['benchmark'] = 90

oil

           date  dcoilwtico  benchmark
0    2013-01-01         NaN         90
1    2013-01-02       93.14         90
2    2013-01-03       92.97         90
3    2013-01-04       93.12         90
4    2013-01-07       93.20         90
...         ...         ...        ...
1213 2017-08-25       47.65         90
1214 2017-08-28       46.40         90
1215 2017-08-29       46.46         90
1216 2017-08-30       45.96         90
1217 2017-08-31       47.26         90

[1218 rows x 3 columns]

In [637]:
oil['benchmark_ratio'] = (oil.loc[:, 'dcoilwtico'] / oil.loc[:, 'benchmark']) * 100

In [639]:
oil

           date  dcoilwtico  benchmark  benchmark_ratio
0    2013-01-01         NaN         90              NaN
1    2013-01-02       93.14         90       103.488889
2    2013-01-03       92.97         90       103.300000
3    2013-01-04       93.12         90       103.466667
4    2013-01-07       93.20         90       103.555556
...         ...         ...        ...              ...
1213 2017-08-25       47.65         90        52.944444
1214 2017-08-28       46.40         90        51.555556
1215 2017-08-29       46.46         90        51.622222
1216 2017-08-30       45.96         90        51.066667
1217 2017-08-31       47.26         90        52.511111

[1218 rows x 4 columns]

In [647]:
oil['buy'] = (oil.loc[:, 'benchmark_ratio'] < 80) * (1000000 / oil.loc[:, 'dcoilwtico'])

oil

           date  dcoilwtico  benchmark  benchmark_ratio           buy
0    2013-01-01         NaN         90              NaN           NaN
1    2013-01-02       93.14         90       103.488889      0.000000
2    2013-01-03       92.97         90       103.300000      0.000000
3    2013-01-04       93.12         90       103.466667      0.000000
4    2013-01-07       93.20         90       103.555556      0.000000
...         ...         ...        ...              ...           ...
1213 2017-08-25       47.65         90        52.944444  20986.358867
1214 2017-08-28       46.40         90        51.555556  21551.724138
1215 2017-08-29       46.46         90        51.622222  21523.891520
1216 2017-08-30       45.96         90        51.066667  21758.050479
1217 2017-08-31       47.26         90        52.511111  21159.542954

[1218 rows x 5 columns]

### Demo

In [ ]:
import pandas as pd

# Load the dataset
df = pd.read_csv('insurance_data.csv')

# Create a new column 'tax_amount' based on conditions
# Assume a tax rate of 5% on the charges for smokers over 18 years old
df['tax_amount'] = (df['smoker'] == 'yes') * (df['age'] > 18) * df['charges'] * 0.05


# Display the DataFrame with the new 'tax_amount' column
df

### Assignment 10

In [652]:
transactions

             date  store_number  transaction_count
1      2013-01-02             1               2111
2      2013-01-02             2               2358
3      2013-01-02             3               3487
4      2013-01-02             4               1922
5      2013-01-02             5               1903
...           ...           ...                ...
83483  2017-08-15            50               2804
83484  2017-08-15            51               1573
83485  2017-08-15            52               2255
83486  2017-08-15            53                932
83487  2017-08-15            54                802

[83487 rows x 3 columns]

In [666]:
transactions['pct_to_target'] = (transactions.loc[:, 'transaction_count'] / 2500)

In [698]:
transactions['met_target'] = transactions.loc[:, 'pct_to_target'] >= 1

In [700]:
transactions

,date,store_number,transaction_count,pct_to_target,met_target,bonus_payable,month,day_of_week
1,2013-01-02,1,2111,0.8444,False,0,1,2
2,2013-01-02,2,2358,0.9432,False,0,1,2
3,2013-01-02,3,3487,1.3948,True,100,1,2
4,2013-01-02,4,1922,0.7688,False,0,1,2
5,2013-01-02,5,1903,0.7612,False,0,1,2
...,...,...,...,...,...,...,...,...
83483,2017-08-15,50,2804,1.1216,True,100,8,15
83484,2017-08-15,51,1573,0.6292,False,0,8,15
83485,2017-08-15,52,2255,0.9020,False,0,8,15
83486,2017-08-15,53,932,0.3728,False,0,8,15
83487,2017-08-15,54,802,0.3208,False,0,8,15

In [702]:
transactions['bonus_payable'] = transactions.loc[:, 'met_target'] * 100

In [704]:
transactions

,date,store_number,transaction_count,pct_to_target,met_target,bonus_payable,month,day_of_week
1,2013-01-02,1,2111,0.8444,False,0,1,2
2,2013-01-02,2,2358,0.9432,False,0,1,2
3,2013-01-02,3,3487,1.3948,True,100,1,2
4,2013-01-02,4,1922,0.7688,False,0,1,2
5,2013-01-02,5,1903,0.7612,False,0,1,2
...,...,...,...,...,...,...,...,...
83483,2017-08-15,50,2804,1.1216,True,100,8,15
83484,2017-08-15,51,1573,0.6292,False,0,8,15
83485,2017-08-15,52,2255,0.9020,False,0,8,15
83486,2017-08-15,53,932,0.3728,False,0,8,15
83487,2017-08-15,54,802,0.3208,False,0,8,15

In [706]:
transactions['month'] = transactions['date'].astype('datetime64[ns]').dt.month

In [708]:
transactions

,date,store_number,transaction_count,pct_to_target,met_target,bonus_payable,month,day_of_week
1,2013-01-02,1,2111,0.8444,False,0,1,2
2,2013-01-02,2,2358,0.9432,False,0,1,2
3,2013-01-02,3,3487,1.3948,True,100,1,2
4,2013-01-02,4,1922,0.7688,False,0,1,2
5,2013-01-02,5,1903,0.7612,False,0,1,2
...,...,...,...,...,...,...,...,...
83483,2017-08-15,50,2804,1.1216,True,100,8,15
83484,2017-08-15,51,1573,0.6292,False,0,8,15
83485,2017-08-15,52,2255,0.9020,False,0,8,15
83486,2017-08-15,53,932,0.3728,False,0,8,15
83487,2017-08-15,54,802,0.3208,False,0,8,15

In [716]:
transactions['day_of_week'] = transactions['date'].astype('datetime64[ns]').dt.dayofweek

In [718]:
transactions

,date,store_number,transaction_count,pct_to_target,met_target,bonus_payable,month,day_of_week
1,2013-01-02,1,2111,0.8444,False,0,1,2
2,2013-01-02,2,2358,0.9432,False,0,1,2
3,2013-01-02,3,3487,1.3948,True,100,1,2
4,2013-01-02,4,1922,0.7688,False,0,1,2
5,2013-01-02,5,1903,0.7612,False,0,1,2
...,...,...,...,...,...,...,...,...
83483,2017-08-15,50,2804,1.1216,True,100,8,1
83484,2017-08-15,51,1573,0.6292,False,0,8,1
83485,2017-08-15,52,2255,0.9020,False,0,8,1
83486,2017-08-15,53,932,0.3728,False,0,8,1
83487,2017-08-15,54,802,0.3208,False,0,8,1

## Advanced Conditional Columns with Select

In [722]:
oil = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\oil.csv")

In [733]:
oil.columns = ['price_date', 'price']

In [735]:
oil

      price_date  price
0     2013-01-01    NaN
1     2013-01-02  93.14
2     2013-01-03  92.97
3     2013-01-04  93.12
4     2013-01-07  93.20
...          ...    ...
1213  2017-08-25  47.65
1214  2017-08-28  46.40
1215  2017-08-29  46.46
1216  2017-08-30  45.96
1217  2017-08-31  47.26

[1218 rows x 2 columns]

In [737]:
import numpy as np

oil['buy'] = np.where(oil['price'] > 100, 'Too High', 'Buy')

oil

      price_date  price  buy
0     2013-01-01    NaN  Buy
1     2013-01-02  93.14  Buy
2     2013-01-03  92.97  Buy
3     2013-01-04  93.12  Buy
4     2013-01-07  93.20  Buy
...          ...    ...  ...
1213  2017-08-25  47.65  Buy
1214  2017-08-28  46.40  Buy
1215  2017-08-29  46.46  Buy
1216  2017-08-30  45.96  Buy
1217  2017-08-31  47.26  Buy

[1218 rows x 3 columns]

In [739]:
oil['buy'].value_counts()

buy
Buy         1036
Too High     182
Name: count, dtype: int64

In [741]:
conditions = [
    (oil['price'] > 100),
    (oil['price'] <= 100) & (oil['price'] > 50),
    (oil['price'] <= 50)
]

choices = ["Don't Buy", "Buy", "Strong Buy"]

oil['buy'] = np.select(conditions, choices, default='Missing')

oil.head()

   price_date  price      buy
0  2013-01-01    NaN  Missing
1  2013-01-02  93.14      Buy
2  2013-01-03  92.97      Buy
3  2013-01-04  93.12      Buy
4  2013-01-07  93.20      Buy

In [743]:
oil['buy'].value_counts()

buy
Buy           512
Strong Buy    481
Don't Buy     182
Missing        43
Name: count, dtype: int64

### Demo

In [ ]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv('insurance_data.csv')

# Define conditions for giving insurance advice
conditions = [
    (df['charges'] > 30000),
    (df['charges'] > 15000) & (df['charges'] <= 30000),
    (df['charges'] <= 15000)
]

# Define choices corresponding to each condition
choices = ["High Cost", "Moderate Cost", "Low Cost"]

# Create a new column 'insurance_advice' using np.select
df['insurance_advice'] = np.select(conditions, choices, default='Missing')

# Display the DataFrame with the new 'insurance_advice' column
df

### Assignment 11

In [756]:
# set up the three conditions
conditions = [
    transactions["month"] == 12,
    (transactions["month"] == 5) & (transactions["day_of_week"] == 6),
    (transactions["month"] == 7) & (transactions["day_of_week"] == 0)
]

# specify outcomes for each condition
choices = ["Holiday Bonus", "Corporate Month", "Summer Special"]

# Call the select method, passing in conditions, choices, and a default value of 'None' if no condition met
transactions["seasonal_bonus"] = np.select(conditions, choices, default="None")

In [760]:
transactions['seasonal_bonus'].value_counts()

seasonal_bonus
None               75258
Holiday Bonus       6028
Summer Special      1103
Corporate Month     1098
Name: count, dtype: int64

## Map Method

In [4]:
import pandas as pd

In [8]:
retail = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\retail_2016_2017.csv")

In [10]:
retail.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [12]:
retail.loc[:, 'family'].value_counts()

family
AUTOMOTIVE                    31968
HOME APPLIANCES               31968
SCHOOL AND OFFICE SUPPLIES    31968
PRODUCE                       31968
PREPARED FOODS                31968
POULTRY                       31968
PLAYERS AND ELECTRONICS       31968
PET SUPPLIES                  31968
PERSONAL CARE                 31968
MEATS                         31968
MAGAZINES                     31968
LIQUOR,WINE,BEER              31968
LINGERIE                      31968
LAWN AND GARDEN               31968
LADIESWEAR                    31968
HOME CARE                     31968
HOME AND KITCHEN II           31968
BABY CARE                     31968
HOME AND KITCHEN I            31968
HARDWARE                      31968
GROCERY II                    31968
GROCERY I                     31968
FROZEN FOODS                  31968
EGGS                          31968
DELI                          31968
DAIRY                         31968
CLEANING                      31968
CELEBRATION                   31968
BREAD/BAKERY                  31968
BOOKS                         31968
BEVERAGES                     31968
BEAUTY                        31968
SEAFOOD                       31968
Name: count, dtype: int64

In [14]:
product_category_dict = {
    'PRODUCE': 'Grocery',
    'POULTRY': 'Grocery',
    'GROCERY I': 'Grocery',
    'GROCERY II': 'Grocery',
    'EGGS': 'Grocery'
}

In [20]:
retail.loc[:, 'family'].map(product_category_dict).value_counts(dropna=False)

family
NaN        895104
Grocery    159840
Name: count, dtype: int64

In [28]:
retail.loc[:, 'family'].map(product_category_dict)

0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
            ...
1054939    Grocery
1054940        NaN
1054941    Grocery
1054942        NaN
1054943        NaN
Name: family, Length: 1054944, dtype: object

## Multiple Column Creation with Assign

In [32]:
retail = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\retail_2016_2017.csv")

In [34]:
sample_df = retail.sample(5, random_state=85)

sample_df

,id,date,store_nbr,family,sales,onpromotion
383220,2329164,2016-08-03,11,MEATS,852.20404,0
883307,2829251,2017-05-11,42,PREPARED FOODS,53.28200,2
656822,2602766,2017-01-04,38,MAGAZINES,4.00000,0
389404,2335348,2016-08-06,35,BOOKS,0.00000,0
216577,2162521,2016-05-01,35,SCHOOL AND OFFICE SUPPLIES,49.00000,7

In [42]:
sample_df.assign(
    onpromotion_flag = sample_df['onpromotion'] > 0,
    family_abbrev = sample_df['family'].str[:3],
    onpromotion_ratio = sample_df['sales'] / sample_df['onpromotion'],
    sales_onprom_target = lambda x: x['onpromotion_ratio'] > 100
).query('sales_onprom_target == True')

,id,date,store_nbr,family,sales,onpromotion,onpromotion_flag,family_abbrev,onpromotion_ratio,sales_onprom_target
383220,2329164,2016-08-03,11,MEATS,852.20404,0,False,MEA,inf,True
656822,2602766,2017-01-04,38,MAGAZINES,4.00000,0,False,MAG,inf,True

In [44]:
sample_df['onpromotion_flag'] = sample_df['onpromotion'] > 0

In [46]:
sample_df

,id,date,store_nbr,family,sales,onpromotion,onpromotion_flag
383220,2329164,2016-08-03,11,MEATS,852.20404,0,False
883307,2829251,2017-05-11,42,PREPARED FOODS,53.28200,2,True
656822,2602766,2017-01-04,38,MAGAZINES,4.00000,0,False
389404,2335348,2016-08-06,35,BOOKS,0.00000,0,False
216577,2162521,2016-05-01,35,SCHOOL AND OFFICE SUPPLIES,49.00000,7,True

### Demo

In [ ]:
import pandas as pd

# Load the dataset
df = pd.read_csv("insurance_data.csv")

# Use the assign method to create new columns
new_df = df.assign(
    sex_abbrev = df['sex'].str[0],
    high_risk = lambda x: (x['sex_abbrev'] == 'm') & (x['bmi'] > 27.5)
)

# Display the DataFrame with new columns

print(new_df[['sex_abbrev', 'high_risk']])

### Assignment 12

In [59]:
import pandas as pd
import numpy as np

transactions = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\transactions.csv")
transactions = transactions.drop(index=transactions.index[0])
transactions

             date  store_nbr  transactions
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
5      2013-01-02          5          1903
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83487 rows x 3 columns]

In [67]:
new_transactions

,date,store_nbr,transactions,pct_to_target,met_target,bonus_payable,month,day_of_week,seasonal_bonus
1,2013-01-02,1,2111,0.8444,False,0,1,2,None
2,2013-01-02,2,2358,0.9432,False,0,1,2,None
3,2013-01-02,3,3487,1.3948,True,100,1,2,None
4,2013-01-02,4,1922,0.7688,False,0,1,2,None
5,2013-01-02,5,1903,0.7612,False,0,1,2,None
...,...,...,...,...,...,...,...,...,...
83483,2017-08-15,50,2804,1.1216,True,100,8,1,None
83484,2017-08-15,51,1573,0.6292,False,0,8,1,None
83485,2017-08-15,52,2255,0.9020,False,0,8,1,None
83486,2017-08-15,53,932,0.3728,False,0,8,1,None
83487,2017-08-15,54,802,0.3208,False,0,8,1,None

In [77]:
new_transactions = transactions.assign(
    pct_to_target = lambda x: x.loc[:, 'transactions'] / 2500,
    met_target = lambda x: x.loc[:, 'pct_to_target'] >= 1,
    bonus_payable = lambda x: x.loc[:, 'met_target'] * 100,
    month = lambda x: x['date'].astype('datetime64[ns]').dt.month,
    day_of_week = lambda x: x['date'].astype('datetime64[ns]').dt.dayofweek,
    seasonal_bonus=lambda x: np.select(
        [
            x['month'] == 12,
            (x['month'] == 5) & (x['day_of_week'] == 6),
            (x['month'] == 7) & (x['day_of_week'] == 0),
        ],
        ["Holiday Bonus", "Corporate Month", "Summer Special"],
        default="None"
    )
)

In [79]:
new_transactions.loc[:,'seasonal_bonus'].value_counts().iloc[1:].sum() * 100

822900

In [91]:
#2nd way of solving the problem
# Create same columns with assign
# Drop columns we created in prior exercises
transactions = transactions.drop(
    [
        "pct_to_target",
        "met_target",
        "bonus_payable",
        "month",
        "day_of_week",
        "seasonal_bonus",
    ],
    axis=1,
)

transactions.head()


transactions = transactions.assign(
    target_pct = transactions["transaction_count"] / 2500,
    met_target = (transactions["transaction_count"] / 2500) >= 1,
    bonus_payable = ((transactions["transaction_count"] / 2500) >= 1) * 100,
    month = transactions.date.dt.month,
    day_of_week = transactions.date.dt.dayofweek,
    seasonal_bonus = np.select(conditions, choices, default="None"),
)

## Categorical Data Type

In [95]:
retail = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\retail_2016_2017.csv")

In [99]:
retail.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  object
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  object
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: float64(1), int64(3), object(2)
memory usage: 151.7 MB

In [101]:
retail = retail.astype({'family': 'category'})

retail.dtypes

id                int64
date             object
store_nbr         int64
family         category
sales           float64
onpromotion       int64
dtype: object

In [103]:
retail.loc[:, 'family'].value_counts()

family
AUTOMOTIVE                    31968
HOME APPLIANCES               31968
SCHOOL AND OFFICE SUPPLIES    31968
PRODUCE                       31968
PREPARED FOODS                31968
POULTRY                       31968
PLAYERS AND ELECTRONICS       31968
PET SUPPLIES                  31968
PERSONAL CARE                 31968
MEATS                         31968
MAGAZINES                     31968
LIQUOR,WINE,BEER              31968
LINGERIE                      31968
LAWN AND GARDEN               31968
LADIESWEAR                    31968
HOME CARE                     31968
HOME AND KITCHEN II           31968
BABY CARE                     31968
HOME AND KITCHEN I            31968
HARDWARE                      31968
GROCERY II                    31968
GROCERY I                     31968
FROZEN FOODS                  31968
EGGS                          31968
DELI                          31968
DAIRY                         31968
CLEANING                      31968
CELEBRATION                   31968
BREAD/BAKERY                  31968
BOOKS                         31968
BEVERAGES                     31968
BEAUTY                        31968
SEAFOOD                       31968
Name: count, dtype: int64

In [105]:
retail.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  object
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  category
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: category(1), float64(1), int64(3), object(1)
memory usage: 92.6 MB

## Type Conversion

In [ ]:
sample_df['sales_int'] = sample_df['sales'].astype('int')

In [ ]:
sample_df = sample_df.astype({'date': 'datatime65(ns)', 'onpromotion': 'float'})

In [110]:
#For price column with formatted as $123 you can do below shown code

In [ ]:
product_df.assign(
    price=product_df['price'].str.strio('$').astype('float')
)