## Basic Aggregations

In [3]:
import pandas as pd

In [31]:
premier_league = pd.read_excel(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\project_data\premier_league_games_full.xlsx")

In [33]:
premier_league.head()

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2

In [35]:
premier_league.sum()

id                                                       9875440
league_name    England Premier LeagueEngland Premier LeagueEn...
season         2008/20092008/20092008/20092008/20092008/20092...
HomeTeam       Manchester UnitedArsenalSunderlandWest Ham Uni...
AwayTeam       Newcastle UnitedWest Bromwich AlbionLiverpoolW...
HomeGoals                                                   4715
AwayGoals                                                   3525
dtype: object

In [37]:
premier_league.mean()

TypeError: Could not convert ['England Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier LeagueEngland Premier

In [39]:
premier_league.loc[:, ['HomeGoals', 'AwayGoals']].mean()

HomeGoals    1.550987
AwayGoals    1.159539
dtype: float64

In [41]:
premier_league.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3040 entries, 0 to 3039
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           3040 non-null   int64
 1   league_name  3040 non-null   object
 2   season       3040 non-null   object
 3   HomeTeam     3040 non-null   object
 4   AwayTeam     3040 non-null   object
 5   HomeGoals    3040 non-null   int64
 6   AwayGoals    3040 non-null   int64
dtypes: int64(3), object(4)
memory usage: 166.4+ KB

## The GroupBy Method

In [45]:
premier_league.groupby("HomeTeam")[['HomeGoals']].mean()

                         HomeGoals
HomeTeam
Arsenal                   2.013158
Aston Villa               1.177632
Birmingham City           1.000000
Blackburn Rovers          1.289474
Blackpool                 1.578947
Bolton Wanderers          1.368421
Bournemouth               1.210526
Burnley                   1.026316
Cardiff City              1.052632
Chelsea                   2.190789
Crystal Palace            1.017544
Everton                   1.697368
Fulham                    1.517544
Hull City                 1.039474
Leicester City            1.657895
Liverpool                 1.934211
Manchester City           2.401316
Manchester United         2.223684
Middlesbrough             0.894737
Newcastle United          1.496241
Norwich City              1.263158
Portsmouth                1.315789
Queens Park Rangers       1.052632
Reading                   1.210526
Southampton               1.763158
Stoke City                1.342105
Sunderland                1.210526
Swansea City              1.421053
Tottenham Hotspur         1.677632
Watford                   1.052632
West Bromwich Albion      1.330827
West Ham United           1.466165
Wigan Athletic            1.115789
Wolverhampton Wanderers   1.087719

In [49]:
premier_league.groupby("HomeTeam")[['HomeGoals']].mean().sort_values('HomeGoals', ascending=False)

                         HomeGoals
HomeTeam
Manchester City           2.401316
Manchester United         2.223684
Chelsea                   2.190789
Arsenal                   2.013158
Liverpool                 1.934211
Southampton               1.763158
Everton                   1.697368
Tottenham Hotspur         1.677632
Leicester City            1.657895
Blackpool                 1.578947
Fulham                    1.517544
Newcastle United          1.496241
West Ham United           1.466165
Swansea City              1.421053
Bolton Wanderers          1.368421
Stoke City                1.342105
West Bromwich Albion      1.330827
Portsmouth                1.315789
Blackburn Rovers          1.289474
Norwich City              1.263158
Reading                   1.210526
Bournemouth               1.210526
Sunderland                1.210526
Aston Villa               1.177632
Wigan Athletic            1.115789
Wolverhampton Wanderers   1.087719
Queens Park Rangers       1.052632
Watford                   1.052632
Cardiff City              1.052632
Hull City                 1.039474
Burnley                   1.026316
Crystal Palace            1.017544
Birmingham City           1.000000
Middlesbrough             0.894737

In [57]:
premier_league.groupby("AwayTeam")[['AwayGoals']].sum().sort_values('AwayGoals', ascending=False)

                         AwayGoals
AwayTeam
Arsenal                        267
Chelsea                        250
Manchester United              244
Manchester City                241
Liverpool                      237
Tottenham Hotspur              226
Everton                        181
Aston Villa                    156
Sunderland                     149
West Ham United                131
West Bromwich Albion           128
Newcastle United               125
Stoke City                     118
Swansea City                    98
Wigan Athletic                  94
Fulham                          92
Southampton                     82
Bolton Wanderers                77
Blackburn Rovers                77
Hull City                       65
Norwich City                    64
Crystal Palace                  61
Wolverhampton Wanderers         56
Queens Park Rangers             55
Leicester City                  51
Birmingham City                 37
Burnley                         31
Blackpool                       25
Portsmouth                      22
Bournemouth                     22
Reading                         20
Watford                         20
Cardiff City                    12
Middlesbrough                   11

### Demo

In [ ]:
import pandas as pd


insurance_df = pd.read_csv('insurance_data.csv')



price_by_region = insurance_df.groupby('region')['charges'].mean()
price_by_region

### Assignment 1

In [67]:
transactions = pd.read_csv(r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\transactions.csv",
                          parse_dates=['date'])

In [69]:
transactions

            date  store_nbr  transactions
0     2013-01-01         25           770
1     2013-01-02          1          2111
2     2013-01-02          2          2358
3     2013-01-02          3          3487
4     2013-01-02          4          1922
...          ...        ...           ...
83483 2017-08-15         50          2804
83484 2017-08-15         51          1573
83485 2017-08-15         52          2255
83486 2017-08-15         53           932
83487 2017-08-15         54           802

[83488 rows x 3 columns]

In [71]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  datetime64[ns]
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 1.9 MB

In [85]:
transactions.groupby('store_nbr')[['transactions']].sum().sort_values('transactions', ascending=False).head(10)

           transactions
store_nbr
44              7273093
47              6535810
45              6201115
46              5990113
3               5366350
48              5107785
8               4637971
49              4574103
50              4384444
11              3972488

## GroupBy Multiple Columns

In [89]:
premier_league

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2
...,...,...,...,...,...,...,...
3035,4764,England Premier League,2015/2016,Southampton,Leicester City,2,2
3036,4765,England Premier League,2015/2016,Swansea City,Stoke City,0,1
3037,4766,England Premier League,2015/2016,Tottenham Hotspur,Liverpool,0,0
3038,4767,England Premier League,2015/2016,Watford,Arsenal,0,3
3039,4768,England Premier League,2015/2016,West Bromwich Albion,Sunderland,1,0

In [95]:
premier_league.groupby(['HomeTeam', 'season'])['HomeGoals'].sum()

HomeTeam                 season
Arsenal                  2008/2009    31
                         2009/2010    48
                         2010/2011    33
                         2011/2012    39
                         2012/2013    47
                                      ..
Wigan Athletic           2011/2012    22
                         2012/2013    26
Wolverhampton Wanderers  2009/2010    13
                         2010/2011    30
                         2011/2012    19
Name: HomeGoals, Length: 160, dtype: int64

In [97]:
premier_league.groupby(['HomeTeam', 'season'])[['HomeGoals']].sum()

                                   HomeGoals
HomeTeam                season
Arsenal                 2008/2009         31
                        2009/2010         48
                        2010/2011         33
                        2011/2012         39
                        2012/2013         47
...                                      ...
Wigan Athletic          2011/2012         22
                        2012/2013         26
Wolverhampton Wanderers 2009/2010         13
                        2010/2011         30
                        2011/2012         19

[160 rows x 1 columns]

In [99]:
premier_league.groupby(['season', 'HomeTeam'])[['HomeGoals']].sum()

                                HomeGoals
season    HomeTeam
2008/2009 Arsenal                      31
          Aston Villa                  27
          Blackburn Rovers             22
          Bolton Wanderers             21
          Chelsea                      33
...                                   ...
2015/2016 Swansea City                 20
          Tottenham Hotspur            35
          Watford                      20
          West Bromwich Albion         20
          West Ham United              34

[160 rows x 1 columns]

In [101]:
premier_league.groupby(['season', 'HomeTeam'], as_index=False)[['HomeGoals']].sum()

        season              HomeTeam  HomeGoals
0    2008/2009               Arsenal         31
1    2008/2009           Aston Villa         27
2    2008/2009      Blackburn Rovers         22
3    2008/2009      Bolton Wanderers         21
4    2008/2009               Chelsea         33
..         ...                   ...        ...
155  2015/2016          Swansea City         20
156  2015/2016     Tottenham Hotspur         35
157  2015/2016               Watford         20
158  2015/2016  West Bromwich Albion         20
159  2015/2016       West Ham United         34

[160 rows x 3 columns]

In [105]:
premier_league.groupby(['season', 'HomeTeam'], as_index=False)[['HomeGoals']].sum().query('HomeTeam == "Arsenal"')

        season HomeTeam  HomeGoals
0    2008/2009  Arsenal         31
20   2009/2010  Arsenal         48
40   2010/2011  Arsenal         33
60   2011/2012  Arsenal         39
80   2012/2013  Arsenal         47
100  2013/2014  Arsenal         36
120  2014/2015  Arsenal         41
140  2015/2016  Arsenal         31

### Demo

In [ ]:
import pandas as pd

# Load the dataset
insurance_df = pd.read_csv('insurance_data.csv')

# Group by 'region' and 'smoker' status, then calculate the average charges directly
grouped_data = insurance_df.groupby(['region', 'smoker'], as_index=False)[['charges']].mean()

# Display the grouped data

grouped_data

### Assignment 2

In [114]:
transactions['month'] = transactions['date'].dt.month

In [116]:
transactions

            date  store_nbr  transactions  month
0     2013-01-01         25           770      1
1     2013-01-02          1          2111      1
2     2013-01-02          2          2358      1
3     2013-01-02          3          3487      1
4     2013-01-02          4          1922      1
...          ...        ...           ...    ...
83483 2017-08-15         50          2804      8
83484 2017-08-15         51          1573      8
83485 2017-08-15         52          2255      8
83486 2017-08-15         53           932      8
83487 2017-08-15         54           802      8

[83488 rows x 4 columns]

In [136]:
transactions.groupby(['store_nbr', 'month'])[['transactions']].sum().sort_values(['month', 'transactions'], ascending=[True, False])

                 transactions
store_nbr month
44        1            628438
47        1            568824
45        1            538370
46        1            522763
3         1            463260
...                       ...
32        12            86167
21        12            84128
42        12            76741
29        12            76627
22        12            50650

[641 rows x 1 columns]

## Multi-Index Dataframe

In [140]:
agg_premier_league = premier_league.groupby(['season', 'HomeTeam'])[['HomeGoals']].sum()

In [142]:
agg_premier_league.head()

                            HomeGoals
season    HomeTeam
2008/2009 Arsenal                  31
          Aston Villa              27
          Blackburn Rovers         22
          Bolton Wanderers         21
          Chelsea                  33

In [144]:
agg_premier_league.loc['2008/2009']

                      HomeGoals
HomeTeam
Arsenal                      31
Aston Villa                  27
Blackburn Rovers             22
Bolton Wanderers             21
Chelsea                      33
Everton                      31
Fulham                       28
Hull City                    18
Liverpool                    41
Manchester City              40
Manchester United            43
Middlesbrough                17
Newcastle United             24
Portsmouth                   26
Stoke City                   22
Sunderland                   21
Tottenham Hotspur            21
West Bromwich Albion         26
West Ham United              23
Wigan Athletic               17

In [146]:
agg_premier_league.loc['2008/2009': '2010/2011']

                                   HomeGoals
season    HomeTeam
2008/2009 Arsenal                         31
          Aston Villa                     27
          Blackburn Rovers                22
          Bolton Wanderers                21
          Chelsea                         33
          Everton                         31
          Fulham                          28
          Hull City                       18
          Liverpool                       41
          Manchester City                 40
          Manchester United               43
          Middlesbrough                   17
          Newcastle United                24
          Portsmouth                      26
          Stoke City                      22
          Sunderland                      21
          Tottenham Hotspur               21
          West Bromwich Albion            26
          West Ham United                 23
          Wigan Athletic                  17
2009/2010 Arsenal                         48
          Aston Villa                     29
          Birmingham City                 19
          Blackburn Rovers                28
          Bolton Wanderers                26
          Burnley                         25
          Chelsea                         68
          Everton                         35
          Fulham                          27
          Hull City                       22
          Liverpool                       43
          Manchester City                 41
          Manchester United               52
          Portsmouth                      24
          Stoke City                      24
          Sunderland                      32
          Tottenham Hotspur               40
          West Ham United                 30
          Wigan Athletic                  19
          Wolverhampton Wanderers         13
2010/2011 Arsenal                         33
          Aston Villa                     26
          Birmingham City                 19
          Blackburn Rovers                22
          Blackpool                       30
          Bolton Wanderers                34
          Chelsea                         39
          Everton                         31
          Fulham                          30
          Liverpool                       37
          Manchester City                 34
          Manchester United               49
          Newcastle United                41
          Stoke City                      31
          Sunderland                      25
          Tottenham Hotspur               30
          West Bromwich Albion            30
          West Ham United                 24
          Wigan Athletic                  22
          Wolverhampton Wanderers         30

In [148]:
agg_premier_league.loc[('2008/2009', 'Arsenal')]

HomeGoals    31
Name: (2008/2009, Arsenal), dtype: int64

In [152]:
agg_premier_league.loc[('2008/2009', 'Arsenal'):('2008/2009', 'Bolton Wanderers')]

                            HomeGoals
season    HomeTeam
2008/2009 Arsenal                  31
          Aston Villa              27
          Blackburn Rovers         22
          Bolton Wanderers         21

In [154]:
agg_premier_league.iloc[:4]

                            HomeGoals
season    HomeTeam
2008/2009 Arsenal                  31
          Aston Villa              27
          Blackburn Rovers         22
          Bolton Wanderers         21

In [158]:
agg_premier_league.iloc[-1]

HomeGoals    34
Name: (2015/2016, West Ham United), dtype: int64

In [160]:
agg_premier_league = premier_league.groupby(['season', 'HomeTeam']).agg({'HomeGoals': ['sum', 'mean']})

In [164]:
agg_premier_league.head()

                           HomeGoals
                                 sum      mean
season    HomeTeam
2008/2009 Arsenal                 31  1.631579
          Aston Villa             27  1.421053
          Blackburn Rovers        22  1.157895
          Bolton Wanderers        21  1.105263
          Chelsea                 33  1.736842

In [166]:
agg_premier_league.iloc[0, 0]

31

In [168]:
agg_premier_league.iloc[1, 1]

1.4210526315789473

In [170]:
agg_premier_league.iloc[1, :]

HomeGoals  sum     27.000000
           mean     1.421053
Name: (2008/2009, Aston Villa), dtype: float64

In [174]:
agg_premier_league.loc['2010/2011', ('HomeGoals', 'mean')]

HomeTeam
Arsenal                    1.736842
Aston Villa                1.368421
Birmingham City            1.000000
Blackburn Rovers           1.157895
Blackpool                  1.578947
Bolton Wanderers           1.789474
Chelsea                    2.052632
Everton                    1.631579
Fulham                     1.578947
Liverpool                  1.947368
Manchester City            1.789474
Manchester United          2.578947
Newcastle United           2.157895
Stoke City                 1.631579
Sunderland                 1.315789
Tottenham Hotspur          1.578947
West Bromwich Albion       1.578947
West Ham United            1.263158
Wigan Athletic             1.157895
Wolverhampton Wanderers    1.578947
Name: (HomeGoals, mean), dtype: float64

## Modifying Multi-Index

In [178]:
agg_premier_league = premier_league.groupby(['season', 'HomeTeam']).agg({'HomeGoals': ['sum', 'mean']})

agg_premier_league

                               HomeGoals
                                     sum      mean
season    HomeTeam
2008/2009 Arsenal                     31  1.631579
          Aston Villa                 27  1.421053
          Blackburn Rovers            22  1.157895
          Bolton Wanderers            21  1.105263
          Chelsea                     33  1.736842
...                                  ...       ...
2015/2016 Swansea City                20  1.052632
          Tottenham Hotspur           35  1.842105
          Watford                     20  1.052632
          West Bromwich Albion        20  1.052632
          West Ham United             34  1.789474

[160 rows x 2 columns]

In [186]:
agg_premier_league = agg_premier_league.droplevel(0, axis=1)

In [188]:
agg_premier_league

                                sum      mean
season    HomeTeam
2008/2009 Arsenal                31  1.631579
          Aston Villa            27  1.421053
          Blackburn Rovers       22  1.157895
          Bolton Wanderers       21  1.105263
          Chelsea                33  1.736842
...                             ...       ...
2015/2016 Swansea City           20  1.052632
          Tottenham Hotspur      35  1.842105
          Watford                20  1.052632
          West Bromwich Albion   20  1.052632
          West Ham United        34  1.789474

[160 rows x 2 columns]

In [190]:
agg_premier_league.swaplevel()

                                sum      mean
HomeTeam             season
Arsenal              2008/2009   31  1.631579
Aston Villa          2008/2009   27  1.421053
Blackburn Rovers     2008/2009   22  1.157895
Bolton Wanderers     2008/2009   21  1.105263
Chelsea              2008/2009   33  1.736842
...                             ...       ...
Swansea City         2015/2016   20  1.052632
Tottenham Hotspur    2015/2016   35  1.842105
Watford              2015/2016   20  1.052632
West Bromwich Albion 2015/2016   20  1.052632
West Ham United      2015/2016   34  1.789474

[160 rows x 2 columns]

In [192]:
agg_premier_league.swaplevel().loc['Arsenal']

           sum      mean
season
2008/2009   31  1.631579
2009/2010   48  2.526316
2010/2011   33  1.736842
2011/2012   39  2.052632
2012/2013   47  2.473684
2013/2014   36  1.894737
2014/2015   41  2.157895
2015/2016   31  1.631579

In [194]:
agg_premier_league.reset_index()

        season              HomeTeam  sum      mean
0    2008/2009               Arsenal   31  1.631579
1    2008/2009           Aston Villa   27  1.421053
2    2008/2009      Blackburn Rovers   22  1.157895
3    2008/2009      Bolton Wanderers   21  1.105263
4    2008/2009               Chelsea   33  1.736842
..         ...                   ...  ...       ...
155  2015/2016          Swansea City   20  1.052632
156  2015/2016     Tottenham Hotspur   35  1.842105
157  2015/2016               Watford   20  1.052632
158  2015/2016  West Bromwich Albion   20  1.052632
159  2015/2016       West Ham United   34  1.789474

[160 rows x 4 columns]

### Demo

In [ ]:
import pandas as pd


# Load the dataset
insurance_df = pd.read_csv('insurance_data.csv')

# Create a MultiIndex DataFrame by grouping and calculating mean charges
multi_index_df = insurance_df.groupby(['region', 'smoker']).agg({'charges': 'mean'})

# Reset the MultiIndex to default integer index
reset_df = multi_index_df.reset_index()

# Display the DataFrame after resetting index
reset_df

### Assignment 3

In [219]:
multi_tran = transactions.groupby(['store_nbr', 'month']).agg({'transactions': ['sum', 'mean']}).sort_values(['month', ('transactions', 'mean')], ascending=[True, False])



multi_tran

                transactions
                         sum         mean
store_nbr month
44        1           628438  4246.202703
47        1           568824  3843.405405
45        1           538370  3637.635135
46        1           522763  3532.182432
3         1           463260  3151.428571
...                      ...          ...
26        12          106919   890.991667
22        12           50650   844.166667
30        12           97665   813.875000
35        12           87296   727.466667
32        12           86167   718.058333

[641 rows x 2 columns]

In [233]:
multi_tran.droplevel(0, axis=1).reset_index().head()

   store_nbr  month     sum         mean
0         44      1  628438  4246.202703
1         47      1  568824  3843.405405
2         45      1  538370  3637.635135
3         46      1  522763  3532.182432
4          3      1  463260  3151.428571

In [238]:
multi_tran.iloc[4]

transactions  sum     463260.000000
              mean      3151.428571
Name: (3, 1), dtype: float64

In [240]:
multi_tran.loc[(3,1)]

transactions  sum     463260.000000
              mean      3151.428571
Name: (3, 1), dtype: float64

In [246]:
multi_tran.iloc[:, [1]]

                transactions
                        mean
store_nbr month
44        1      4246.202703
47        1      3843.405405
45        1      3637.635135
46        1      3532.182432
3         1      3151.428571
...                      ...
26        12      890.991667
22        12      844.166667
30        12      813.875000
35        12      727.466667
32        12      718.058333

[641 rows x 1 columns]

In [252]:
multi_tran.loc[:, [('transactions', 'mean')]]

                transactions
                        mean
store_nbr month
44        1      4246.202703
47        1      3843.405405
45        1      3637.635135
46        1      3532.182432
3         1      3151.428571
...                      ...
26        12      890.991667
22        12      844.166667
30        12      813.875000
35        12      727.466667
32        12      718.058333

[641 rows x 1 columns]

In [254]:
multi_tran.droplevel(0, axis=1).reset_index()

     store_nbr  month     sum         mean
0           44      1  628438  4246.202703
1           47      1  568824  3843.405405
2           45      1  538370  3637.635135
3           46      1  522763  3532.182432
4            3      1  463260  3151.428571
..         ...    ...     ...          ...
636         26     12  106919   890.991667
637         22     12   50650   844.166667
638         30     12   97665   813.875000
639         35     12   87296   727.466667
640         32     12   86167   718.058333

[641 rows x 4 columns]

## Agg Method & Names Aggregations

In [284]:
premier_league[['season', 'HomeTeam', 'id', 'HomeGoals', 'AwayGoals']].groupby(['season', 'HomeTeam']).agg(['sum', 'mean'])

                                   id              HomeGoals            \
                                  sum         mean       sum      mean
season    HomeTeam
2008/2009 Arsenal               36128  1901.473684        31  1.631579
          Aston Villa           36136  1901.894737        27  1.421053
          Blackburn Rovers      36781  1935.842105        22  1.157895
          Bolton Wanderers      36214  1906.000000        21  1.105263
          Chelsea               36552  1923.789474        33  1.736842
...                               ...          ...       ...       ...
2015/2016 Swansea City          87241  4591.631579        20  1.052632
          Tottenham Hotspur     87218  4590.421053        35  1.842105
          Watford               87142  4586.421053        20  1.052632
          West Bromwich Albion  87064  4582.315789        20  1.052632
          West Ham United       86965  4577.105263        34  1.789474

                               AwayGoals
                                     sum      mean
season    HomeTeam
2008/2009 Arsenal                     16  0.842105
          Aston Villa                 21  1.105263
          Blackburn Rovers            23  1.210526
          Bolton Wanderers            21  1.105263
          Chelsea                     12  0.631579
...                                  ...       ...
2015/2016 Swansea City                20  1.052632
          Tottenham Hotspur           15  0.789474
          Watford                     19  1.000000
          West Bromwich Albion        26  1.368421
          West Ham United             26  1.368421

[160 rows x 6 columns]

In [288]:
(premier_league[['season', 'HomeTeam', 'id', 'HomeGoals', 'AwayGoals']]
 .groupby(['season', 'HomeTeam'])
 .agg({'HomeGoals': ['sum', 'mean'], 'AwayGoals': ['sum', 'mean']}))

                               HomeGoals           AwayGoals
                                     sum      mean       sum      mean
season    HomeTeam
2008/2009 Arsenal                     31  1.631579        16  0.842105
          Aston Villa                 27  1.421053        21  1.105263
          Blackburn Rovers            22  1.157895        23  1.210526
          Bolton Wanderers            21  1.105263        21  1.105263
          Chelsea                     33  1.736842        12  0.631579
...                                  ...       ...       ...       ...
2015/2016 Swansea City                20  1.052632        20  1.052632
          Tottenham Hotspur           35  1.842105        15  0.789474
          Watford                     20  1.052632        19  1.000000
          West Bromwich Albion        20  1.052632        26  1.368421
          West Ham United             34  1.789474        26  1.368421

[160 rows x 4 columns]

In [294]:
(premier_league[['season', 'HomeTeam', 'id', 'HomeGoals', 'AwayGoals']]
 .groupby(['season', 'HomeTeam'], as_index=False)
 .agg(home_goal_sum = ('HomeGoals', 'sum'),
      away_goal_sum = ('AwayGoals', 'sum')))

        season              HomeTeam  home_goal_sum  away_goal_sum
0    2008/2009               Arsenal             31             16
1    2008/2009           Aston Villa             27             21
2    2008/2009      Blackburn Rovers             22             23
3    2008/2009      Bolton Wanderers             21             21
4    2008/2009               Chelsea             33             12
..         ...                   ...            ...            ...
155  2015/2016          Swansea City             20             20
156  2015/2016     Tottenham Hotspur             35             15
157  2015/2016               Watford             20             19
158  2015/2016  West Bromwich Albion             20             26
159  2015/2016       West Ham United             34             26

[160 rows x 4 columns]

### Demo

In [ ]:
import pandas as pd

# Load the dataset
insurance_df = pd.read_csv('insurance_data.csv')

# Group by 'region' and 'smoker', then calculate multiple aggregations
aggregated_data = insurance_df.groupby(['region', 'smoker']).agg(
    average_charges = ('charges', 'mean'),
    total_charges = ('charges', 'sum'),
    max_children = ('children', 'max')
)

# Display the aggregated data
aggregated_data

### Assignment 4

In [300]:
# Recreate table from section 3

transactions2 = transactions.assign(
    target_pct=transactions["transactions"] / 2500,
    met_target=(transactions["transactions"] / 2500) >= 1,
    bonus_payable=((transactions["transactions"] / 2500) >= 1) * 100,
    month=transactions.date.dt.month,
    day_of_week=transactions.date.dt.dayofweek,
)

transactions2.head()

,date,store_nbr,transactions,month,target_pct,met_target,bonus_payable,day_of_week
0,2013-01-01,25,770,1,0.3080,False,0,1
1,2013-01-02,1,2111,1,0.8444,False,0,2
2,2013-01-02,2,2358,1,0.9432,False,0,2
3,2013-01-02,3,3487,1,1.3948,True,100,2
4,2013-01-02,4,1922,1,0.7688,False,0,2

In [310]:
(transactions2.groupby('store_nbr')
 .agg(
     met_target = ('met_target', 'mean'),
     bonus_payable = ('bonus_payable', 'sum')
 )
 .sort_values('bonus_payable', ascending=False)
 .head()
)

           met_target  bonus_payable
store_nbr
47           0.999404         167600
44           0.998807         167500
45           0.997615         167300
3            0.998210         167300
46           0.989267         165900

In [314]:
(transactions2.groupby('month')
 .agg(
     met_target = ('met_target', 'mean'),
     bonus_payable = ('bonus_payable', 'sum')
 )
 .sort_values('bonus_payable', ascending=False)
 .head()
)

       met_target  bonus_payable
month
12       0.255640         154100
5        0.170792         131800
3        0.169461         130400
4        0.174469         129700
7        0.162486         126300

In [320]:
(transactions2.groupby('day_of_week')
 .agg(
     met_target = ('met_target', 'mean'),
     bonus_payable = ('bonus_payable', 'sum')
 )
 .sort_values('bonus_payable', ascending=False)
 .head()
)

             met_target  bonus_payable
day_of_week
5              0.222204         266400
6              0.204001         241700
4              0.179007         213000
0              0.160214         191600
2              0.160572         191000

## Transforming Dataframes

In [326]:
premier_league.head()

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2

In [334]:
pm = premier_league.assign(
    avg_team_goals = premier_league.groupby(['HomeTeam'])['HomeGoals'].transform('mean'),
    difference = lambda x: x['HomeGoals'] - x['avg_team_goals']

)

pm

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals,avg_team_goals,difference
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1,2.223684,-1.223684
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0,2.013158,-1.013158
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1,1.210526,-1.210526
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1,1.466165,0.533835
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2,1.177632,2.822368
...,...,...,...,...,...,...,...,...,...
3035,4764,England Premier League,2015/2016,Southampton,Leicester City,2,2,1.763158,0.236842
3036,4765,England Premier League,2015/2016,Swansea City,Stoke City,0,1,1.421053,-1.421053
3037,4766,England Premier League,2015/2016,Tottenham Hotspur,Liverpool,0,0,1.677632,-1.677632
3038,4767,England Premier League,2015/2016,Watford,Arsenal,0,3,1.052632,-1.052632
3039,4768,England Premier League,2015/2016,West Bromwich Albion,Sunderland,1,0,1.330827,-0.330827

In [336]:
pm.groupby(['HomeTeam', 'AwayTeam']).agg({'difference': 'mean'}).sort_values('difference')

                                             difference
HomeTeam                AwayTeam
Chelsea                 Bournemouth           -2.190789
Southampton             Wigan Athletic        -1.763158
                        Cardiff City          -1.763158
Leicester City          Hull City             -1.657895
                        Manchester City       -1.657895
...                                                 ...
Wolverhampton Wanderers Blackpool              2.912281
Fulham                  Queens Park Rangers    2.982456
Everton                 Blackpool              3.302632
Leicester City          Queens Park Rangers    3.342105
Arsenal                 Blackpool              3.986842

[932 rows x 1 columns]

In [342]:
pm.query('HomeTeam == "Arsenal" and AwayTeam == "Blackpool"')

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals,avg_team_goals,difference
870,2599,England Premier League,2010/2011,Arsenal,Blackpool,6,0,2.013158,3.986842

### Demo

In [ ]:
import pandas as pd

# Load the dataset
insurance_df = pd.read_csv('insurance_data.csv')


# Use transform within assign to add group-level total charges to each row
insurance_df = insurance_df.assign(total_region_charges = insurance_df.groupby('region')['charges'].transform('sum'))


# Display the DataFrame with the new col
insurance_df

### Assignment 5

In [347]:
transactions2

,date,store_nbr,transactions,month,target_pct,met_target,bonus_payable,day_of_week
0,2013-01-01,25,770,1,0.3080,False,0,1
1,2013-01-02,1,2111,1,0.8444,False,0,2
2,2013-01-02,2,2358,1,0.9432,False,0,2
3,2013-01-02,3,3487,1,1.3948,True,100,2
4,2013-01-02,4,1922,1,0.7688,False,0,2
...,...,...,...,...,...,...,...,...
83483,2017-08-15,50,2804,8,1.1216,True,100,1
83484,2017-08-15,51,1573,8,0.6292,False,0,1
83485,2017-08-15,52,2255,8,0.9020,False,0,1
83486,2017-08-15,53,932,8,0.3728,False,0,1
83487,2017-08-15,54,802,8,0.3208,False,0,1

In [365]:
transactions2.assign(
    store_avg_trans = transactions2.groupby(['store_nbr', 'day_of_week'])['transactions'].transform('mean'),
    trans_vs_avg = lambda x: x['transactions'] - x['store_avg_trans']
).head()

,date,store_nbr,transactions,month,target_pct,met_target,bonus_payable,day_of_week,store_avg_trans,trans_vs_avg
0,2013-01-01,25,770,1,0.3080,False,0,1,740.245690,29.754310
1,2013-01-02,1,2111,1,0.8444,False,0,2,1870.782427,240.217573
2,2013-01-02,2,2358,1,0.9432,False,0,2,1952.652720,405.347280
3,2013-01-02,3,3487,1,1.3948,True,100,2,3142.682008,344.317992
4,2013-01-02,4,1922,1,0.7688,False,0,2,1499.569038,422.430962

## Pivot Table

In [369]:
premier_league.head()

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2

In [371]:
premier_league.pivot_table(
    index='HomeTeam',
    columns='season',
    values='HomeGoals',
    aggfunc='sum'
)

season,2008/2009,2009/2010,2010/2011,2011/2012,2012/2013,2013/2014,2014/2015,2015/2016
HomeTeam,,,,,,,,
Arsenal,31.0,48.0,33.0,39.0,47.0,36.0,41.0,31.0
Aston Villa,27.0,29.0,26.0,20.0,23.0,22.0,18.0,14.0
Birmingham City,NaN,19.0,19.0,NaN,NaN,NaN,NaN,NaN
Blackburn Rovers,22.0,28.0,22.0,26.0,NaN,NaN,NaN,NaN
Blackpool,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN
Bolton Wanderers,21.0,26.0,34.0,23.0,NaN,NaN,NaN,NaN
Bournemouth,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0
Burnley,NaN,25.0,NaN,NaN,NaN,NaN,14.0,NaN
Cardiff City,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN
Chelsea,33.0,68.0,39.0,41.0,41.0,43.0,36.0,32.0
Crystal Palace,NaN,NaN,NaN,NaN,NaN,18.0,21.0,19.0
Everton,31.0,35.0,31.0,28.0,33.0,38.0,27.0,35.0
Fulham,28.0,27.0,30.0,36.0,28.0,24.0,NaN,NaN
Hull City,18.0,22.0,NaN,NaN,NaN,20.0,19.0,NaN
Leicester City,NaN,NaN,NaN,NaN,NaN,NaN,28.0,35.0
Liverpool,41.0,43.0,37.0,24.0,33.0,53.0,30.0,33.0
Manchester City,40.0,41.0,34.0,55.0,41.0,63.0,44.0,47.0
Manchester United,43.0,52.0,49.0,52.0,45.0,29.0,41.0,27.0
Middlesbrough,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Newcastle United,24.0,NaN,41.0,29.0,24.0,23.0,26.0,32.0
Norwich City,NaN,NaN,NaN,28.0,25.0,17.0,NaN,26.0
Portsmouth,26.0,24.0,NaN,NaN,NaN,NaN,NaN,NaN
Queens Park Rangers,NaN,NaN,NaN,24.0,13.0,NaN,23.0,NaN
Reading,NaN,NaN,NaN,NaN,23.0,NaN,NaN,NaN
Southampton,NaN,NaN,NaN,NaN,26.0,32.0,37.0,39.0
Stoke City,22.0,24.0,31.0,25.0,21.0,27.0,32.0,22.0
Sunderland,21.0,32.0,25.0,26.0,20.0,21.0,16.0,23.0
Swansea City,NaN,NaN,NaN,27.0,28.0,33.0,27.0,20.0
Tottenham Hotspur,21.0,40.0,30.0,39.0,29.0,30.0,31.0,35.0
Watford,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0
West Bromwich Albion,26.0,NaN,30.0,21.0,32.0,24.0,24.0,20.0
West Ham United,23.0,30.0,24.0,NaN,34.0,25.0,25.0,34.0
Wigan Athletic,17.0,19.0,22.0,22.0,26.0,NaN,NaN,NaN
Wolverhampton Wanderers,NaN,13.0,30.0,19.0,NaN,NaN,NaN,NaN

In [375]:
premier_league.query("HomeTeam in ['Arsenal', 'Chelsea', 'Everton']").pivot_table(
    index='HomeTeam',
    columns='season',
    values='HomeGoals',
    aggfunc='sum'
)

season,2008/2009,2009/2010,2010/2011,2011/2012,2012/2013,2013/2014,2014/2015,2015/2016
HomeTeam,,,,,,,,
Arsenal,31,48,33,39,47,36,41,31
Chelsea,33,68,39,41,41,43,36,32
Everton,31,35,31,28,33,38,27,35

In [377]:
premier_league.query("HomeTeam in ['Arsenal', 'Chelsea', 'Everton']").pivot_table(
    index='HomeTeam',
    columns='season',
    values='HomeGoals',
    aggfunc='sum',
    margins=True
)

season,2008/2009,2009/2010,2010/2011,2011/2012,2012/2013,2013/2014,2014/2015,2015/2016,All
HomeTeam,,,,,,,,,
Arsenal,31,48,33,39,47,36,41,31,306
Chelsea,33,68,39,41,41,43,36,32,333
Everton,31,35,31,28,33,38,27,35,258
All,95,151,103,108,121,117,104,98,897

In [379]:
premier_league.query("HomeTeam in ['Arsenal', 'Chelsea', 'Everton']").pivot_table(
    index='HomeTeam',
    columns='season',
    values='HomeGoals',
    aggfunc='mean',
    margins=True
)

season,2008/2009,2009/2010,2010/2011,2011/2012,2012/2013,2013/2014,2014/2015,2015/2016,All
HomeTeam,,,,,,,,,
Arsenal,1.631579,2.526316,1.736842,2.052632,2.473684,1.894737,2.157895,1.631579,2.013158
Chelsea,1.736842,3.578947,2.052632,2.157895,2.157895,2.263158,1.894737,1.684211,2.190789
Everton,1.631579,1.842105,1.631579,1.473684,1.736842,2.000000,1.421053,1.842105,1.697368
All,1.666667,2.649123,1.807018,1.894737,2.122807,2.052632,1.824561,1.719298,1.967105

### Demo

In [ ]:
import pandas as pd

# Load the dataset
insurance_data = pd.read_csv('insurance_data.csv')


# Create a pivot table to summarise charges for the filtered data by region and smoker status
pivot_table = insurance_data.query("region in ['southeast', 'northwest'] and smoker == 'yes'").pivot_table(
    index='bmi',
    columns='region',
    values='charges',
    aggfunc='sum'
)


# Display the pivot table

pivot_table

## Multiple Aggregation Pivot Tables

In [386]:
premier_league.query("HomeTeam in ['Arsenal', 'Chelsea', 'Everton']").pivot_table(
    index='HomeTeam',
    columns='season',
    values='HomeGoals',
    aggfunc=('mean', 'sum')
)

              mean                                                    \
season   2008/2009 2009/2010 2010/2011 2011/2012 2012/2013 2013/2014
HomeTeam
Arsenal   1.631579  2.526316  1.736842  2.052632  2.473684  1.894737
Chelsea   1.736842  3.578947  2.052632  2.157895  2.157895  2.263158
Everton   1.631579  1.842105  1.631579  1.473684  1.736842  2.000000

                                   sum                                \
season   2014/2015 2015/2016 2008/2009 2009/2010 2010/2011 2011/2012
HomeTeam
Arsenal   2.157895  1.631579        31        48        33        39
Chelsea   1.894737  1.684211        33        68        39        41
Everton   1.421053  1.842105        31        35        31        28


season   2012/2013 2013/2014 2014/2015 2015/2016
HomeTeam
Arsenal         47        36        41        31
Chelsea         41        43        36        32
Everton         33        38        27        35

In [392]:
premier_league.query("HomeTeam in ['Arsenal', 'Chelsea', 'Everton']").pivot_table(
    index='HomeTeam',
    columns='season',
    aggfunc=({'HomeGoals': ['mean', 'sum'], 'AwayGoals': ['mean', 'sum']})
)

         AwayGoals                                                    \
              mean
season   2008/2009 2009/2010 2010/2011 2011/2012 2012/2013 2013/2014
HomeTeam
Arsenal   0.842105  0.789474  0.789474  0.894737  1.210526  0.578947
Chelsea   0.631579  0.736842  0.684211  1.263158  0.842105  0.578947
Everton   1.052632  1.105263  1.210526  0.789474  0.894737  1.000000

                                                  ... HomeGoals            \
                                   sum            ...      mean
season   2014/2015 2015/2016 2008/2009 2009/2010  ... 2014/2015 2015/2016
HomeTeam                                          ...
Arsenal   0.736842  0.578947        16        15  ...  2.157895  1.631579
Chelsea   0.473684  1.578947        12        14  ...  1.894737  1.684211
Everton   1.105263  1.578947        20        21  ...  1.421053  1.842105

                                                                      \
               sum
season   2008/2009 2009/2010 2010/2011 2011/2012 2012/2013 2013/2014
HomeTeam
Arsenal         31        48        33        39        47        36
Chelsea         33        68        39        41        41        43
Everton         31        35        31        28        33        38



season   2014/2015 2015/2016
HomeTeam
Arsenal         41        31
Chelsea         36        32
Everton         27        35

[3 rows x 32 columns]

## Pivot Table Heatmaps

In [400]:
premier_league.query("HomeTeam in ['Arsenal', 'Chelsea', 'Everton']").pivot_table(
    index='HomeTeam',
    columns='season',
    values='HomeGoals',
    aggfunc='mean',
    margins=True
).style.background_gradient(cmap="RdYlGn", axis=None)

In [404]:
premier_league.query("HomeTeam in ['Arsenal', 'Chelsea', 'Everton']").pivot_table(
    index='HomeTeam',
    columns='season',
    values='HomeGoals',
    aggfunc='mean',
    margins=True
).style.background_gradient(cmap="RdYlGn", axis=0) #Column Level

In [408]:
premier_league.query("HomeTeam in ['Arsenal', 'Chelsea', 'Everton']").pivot_table(
    index='HomeTeam',
    columns='season',
    values='HomeGoals',
    aggfunc='mean',
    margins=True
).style.background_gradient(cmap="RdYlGn", axis=1) #Row Level

## Melting Dataframes

In [414]:
pm2 = premier_league.query("HomeTeam in ['Arsenal', 'Chelsea', 'Everton']").pivot_table(
    index='HomeTeam',
    columns='season',
    values='HomeGoals',
    aggfunc='sum'
)

In [416]:
pm2

season,2008/2009,2009/2010,2010/2011,2011/2012,2012/2013,2013/2014,2014/2015,2015/2016
HomeTeam,,,,,,,,
Arsenal,31,48,33,39,47,36,41,31
Chelsea,33,68,39,41,41,43,36,32
Everton,31,35,31,28,33,38,27,35

In [430]:
pm2.reset_index().melt(
    id_vars='HomeTeam',
    value_vars=['2008/2009', '2009/2010', '2010/2011'],
    value_name='avg_goals'
)

  HomeTeam     season  avg_goals
0  Arsenal  2008/2009         31
1  Chelsea  2008/2009         33
2  Everton  2008/2009         31
3  Arsenal  2009/2010         48
4  Chelsea  2009/2010         68
5  Everton  2009/2010         35
6  Arsenal  2010/2011         33
7  Chelsea  2010/2011         39
8  Everton  2010/2011         31

### Demo

In [ ]:
import pandas as pd

# Load the dataset
melted_insurance_df = pd.read_csv('melted_insurance_df.csv')


# Melt the wide table to a long format
long_format_df = melted_insurance_df.melt(
    id_vars='region',
    var_name='metric_age',
    value_name='value'
)


# Display the melted DataFrame
long_format_df

### Assignment 6

In [438]:
transactions3 = transactions2.assign(
    store_avg_trans = transactions2.groupby(['store_nbr', 'day_of_week'])['transactions'].transform('mean'),
    trans_vs_avg = lambda x: x['transactions'] - x['store_avg_trans']
)

In [440]:
transactions3

,date,store_nbr,transactions,month,target_pct,met_target,bonus_payable,day_of_week,store_avg_trans,trans_vs_avg
0,2013-01-01,25,770,1,0.3080,False,0,1,740.245690,29.754310
1,2013-01-02,1,2111,1,0.8444,False,0,2,1870.782427,240.217573
2,2013-01-02,2,2358,1,0.9432,False,0,2,1952.652720,405.347280
3,2013-01-02,3,3487,1,1.3948,True,100,2,3142.682008,344.317992
4,2013-01-02,4,1922,1,0.7688,False,0,2,1499.569038,422.430962
...,...,...,...,...,...,...,...,...,...,...
83483,2017-08-15,50,2804,8,1.1216,True,100,1,2342.410788,461.589212
83484,2017-08-15,51,1573,8,0.6292,False,0,1,1548.448133,24.551867
83485,2017-08-15,52,2255,8,0.9020,False,0,1,1892.588235,362.411765
83486,2017-08-15,53,932,8,0.3728,False,0,1,877.214286,54.785714
83487,2017-08-15,54,802,8,0.3208,False,0,1,817.721992,-15.721992

In [468]:
transactions3[transactions3['bonus_payable'] != 0].pivot_table(
    index='store_nbr',
    columns='day_of_week',
    values='bonus_payable',
    aggfunc='sum'
).iloc[:10].style.background_gradient(cmap="RdYlGn", axis=1) #Column Level

In [472]:
transactions3[transactions3['bonus_payable'] != 0].pivot_table(
    index='store_nbr',
    columns='day_of_week',
    values='bonus_payable',
    aggfunc='sum'
).reset_index().melt(
    id_vars='store_nbr',
    value_name='bonus_payable'
).head()

   store_nbr day_of_week  bonus_payable
0          1           0          200.0
1          2           0          300.0
2          3           0        24000.0
3          4           0          200.0
4          5           0          200.0